### ISSUE TITLE
App crashes if the MongoDB service is not READY on startup

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/health-blockchain#19]
If the MongoDB service is not in a READY state when the app starts, the app crashes when it tries to connect to mongo:

```
/home/vcap/app/node_modules/mongodb/lib/mongos.js:256
May 17, 2017 05:46:32.625 PM APP/0  at Timeout.<anonymous> (/home/vcap/app/node_modules/mongodb-core/lib/topologies/mongos.js:638:28)
May 17, 2017 05:46:32.628 PM APP/0  at tryOnTimeout (timers.js:244:5)
May 17, 2017 05:46:32.628 PM APP/0  at Timer.listOnTimeout (timers.js:214:5)
May 17, 2017 05:46:32.628 PM APP/0  at ontimeout (timers.js:380:14)
May 17, 2017 05:46:32.628 PM APP/0 MongoError: no mongos proxy available
May 17, 2017 05:46:32.628 PM APP/0 npm ERR! Linux 4.4.0-45-generic
May 17, 2017 05:46:32.697 PM APP/0 npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
May 17, 2017 05:46:32.697 PM APP/0 npm ERR! node v6.10.2
May 17, 2017 05:46:32.697 PM APP/0 npm ERR! npm v3.10.10
May 17, 2017 05:46:32.698 PM APP/0 npm ERR! Failed at the NodejsStarterApp@0.0.1 start script 'node app.js'.
May 17, 2017 05:46:32.699 PM APP/0 npm ERR! code ELIFECYCLE
May 17, 2017 05:46:32.699 PM APP/0 npm ERR! NodejsStarterApp@0.0.1 start: `node app.js`
May 17, 2017 05:46:32.699 PM APP/0 npm ERR! Exit status 1
May 17, 2017 05:46:32.699 PM APP/0 npm ERR!
```

The app should retry / delay the database initialization and not crash if the database is not yet available (or if the connection is lost).

**Comment by antonmc** [comment]
I've added some code to stop it crashing at least

We'll need to figure out how best to handle a delay

**Comment by antonmc** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/4783b745-d26b-41fe-bb56-d39169880c89 "fitchain"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/420a436e-add5-49fe-9817-1556990ec503 "fitchain") deployed [health-blockchain](https://github.com/IBM-Bluemix/health-blockchain/releases/tag/deploy-ibm-yp-us-south-Dev-Advocates-demos-20170517-193528 "deploy-ibm-yp-us-south-Dev-Advocates-demos-20170517-193528") to [demos](https://console.ng.bluemix.net/apps/a40dc60e-7166-458d-af16-edeb22da5c9d?env_id=ibm:yp:us-south "ibm:yp:us-south:Dev-Advocates:demos"), including commit bcf40cfb2b14c4ba0b4e6571e3e46acaadd9f95d

**Comment by l2fprod** [comment]
#26 should supersede this.
