### ISSUE TITLE
Create Toolchain button broken

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/health-blockchain#25]
![image](https://cloud.githubusercontent.com/assets/5502967/26259016/bff5598a-3c8c-11e7-93ec-82f3ddf7fef5.png)

**Comment by l2fprod** [comment]
@rvennam can you detail the steps? Maybe record them.

I just click the create toolchain button and could create a toolchain with no issue.

**Comment by rvennam** [comment]
https://www.dropbox.com/s/nizaxenwap82syc/ToolchainBug.mov?dl=0

**Comment by l2fprod** [comment]
@rvennam sounds like an issue with toolchain that does not redirect you to the login page. Can you try when you are logged in Bluemix?

**Comment by l2fprod** [comment]
toolchain was expecting at least an empty "parameters: {}"
https://github.com/IBM-Bluemix/health-blockchain/commit/5a3e299389b068a729b830a3ed45a0906bc90121
